name: Test GitHub Token

on: [push]

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test GITHUB_TOKEN
      run: |
        echo "Testing GITHUB_TOKEN"
        echo ${{ secrets.GITHUB_TOKEN }}
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
