name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间凌晨 1 点自动同步
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your forked repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 禁用默认的 GitHub 凭据

    # Step 2: Set up Git configuration
    - name: Set up Git
      run: |
        git config user.name "sauwastika"
        git config user.email "156944310+sauwastika@users.noreply.github.com"

    # Step 3: Add upstream repository and fetch updates
    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/YueChan/Live.git
        git fetch upstream
        git checkout main
        git merge upstream/main --allow-unrelated-histories

    # Step 4: Push changes to your fork on GitHub
    - name: Push changes to fork
      run: |
        git merge upstream/main --no-edit
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
