name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日运行
  workflow_dispatch: # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20' # 显式指定 Node.js 版本
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "sauwastika"
        git config user.email "www@sauwastika.com"

    - name: Add upstream
      run: git remote add upstream https://github.com/YueChan/Live.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main --no-edit

    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
